apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app:  myapp-service
spec:
  selector:
    app: myjavawebapp
  type: NodePort
  ports:
  - nodePort: 9090
      port: 8080
      targetPort: 8080
